### ISSUE TITLE
Possible to change color of right click menu border instead of removing it for Windows 10?

### ISSUE THREAD

**Issue by PkChris** [krlvm/AcrylicMenus#16]
Just wondering if it's possible to change the color of the right click menu border instead of removing it for Windows 10. If it has to transition the same way, changing the color to a shade of gray may look less glaring and still improve the look of the menus.

**Comment by krlvm** [comment]
Yes, it is possible with modifying [this](https://github.com/krlvm/AcrylicMenus/blob/47544e08339254dea6d84977ffeec21fac31195b/AcrylicMenus/WindowHelper.h#L69) line.
There's actually some problems with transition animation, so I think I need to remove it.

**Comment by PkChris** [comment]
> Yes, it is possible with modifying [this](https://github.com/krlvm/AcrylicMenus/blob/47544e08339254dea6d84977ffeec21fac31195b/AcrylicMenus/WindowHelper.h#L69) line. There's actually some problems with transition animation, so I think I need to remove it.

Sorry for the late reply. Sounds like it would need to be implemented using the same method as removing the border so it'd probably look just as janky?

**Comment by krlvm** [comment]
Yes, it will be noticeable anyway

**Comment by PkChris** [comment]
Ah doesn't sound like it'd help then. Thanks for entertaining the idea at least.

**Comment by krlvm** [comment]
This was mitigated in recent TranslucentFlyouts versions and I ported the fix to [v1.8.0](https://github.com/krlvm/AcrylicMenus/releases/tag/v1.0.8).

TranslucentFlyouts made a big step forward and as a hardcoding fan I'm amazed - I can even reproduce my preferred configuration in the latest version without the need for a rebuild - all through the configuration.

So, I've added a [deprecation notice](https://github.com/krlvm/AcrylicMenus#-current-project-status) to the README, and even more recommend that people prefer TranslucentFlyouts over AcrylicMenus. I will no longer release updates for AcrylicMenus, especially since it is now feature-complete for my taste - except for fixes if it breaks for some reason.

Thanks to @ALTaleX531 for the great work - it's just a masterpiece!
