### ISSUE TITLE
Suggested to apply acrylic to all apps

### ISSUE THREAD

**Issue by shamodeyu** [krlvm/AcrylicMenus#22]
Thanks for developing the good app.
Look beautiful on my PC.

![2023-03-15 09 47 05](https://user-images.githubusercontent.com/123850195/225183520-59e91683-b394-4700-84e0-9a7235b64afc.png)

I suggested the acrylic effect can be applied on every apps and with blue backgroud as shown on above picture.

![2023-03-14 15 49 03](https://user-images.githubusercontent.com/123850195/225183247-e105951e-1246-4606-bf34-7ebb54236f4f.png)

**Comment by krlvm** [comment]
This is not a blue background, this is the result of blurring menu backdrop, which is blue.

We can't apply acrylic effect to every menu, but to those that we can - it is not very stable and does not always work properly due to the way it works. For that you can use TranslucentFlyouts, which is also more customisable.
