### ISSUE TITLE
Does AcrylicMenus retain ANY advantages over TranslucentFlyouts? (e.g. stability, performance...?)

### ISSUE THREAD

**Issue by e-t-l** [krlvm/AcrylicMenus#27]
I have a question about switching to TranslucentFlouts
> Now the latest versions of TranslucentFlyouts support everything that was missing

In the ReadMe, you had previously written:
> For minimal performance impact, all settings are hardcoded
> [...]
> AcrylicMenus supports all Win32 applications, excluding legacy and custom (ownerdrawn) popup menus, however, currently, for maximum stability and avoiding incompatibilities,

Does AcrylicMenus still have better performance, better stability, less incompatibility, or ANY other advantages compared to TranslucentFlyouts?

**Comment by krlvm** [comment]
AcrylicMenus is just an opinionated fork of TranslucentFlyouts, which looks like what I think these menus should look like. It was impossible to achieve this in the original version of TF, so I made the appropriate changes to the source code, at the same time removing customizability, because supporting it was not my goal.

Now this look can be achieved by customizing TF, so there's no more need in maintaining this fork.

I don't remember if it is possible to configure this in TF now, but previously it was injected into all processes, which led to crashes of various programs. Apart from Explorer, I personally didn’t need such functionality anywhere, so I limited it to Explorer. Now there seems to be no such problem there.

If there is a performance advantage, it is measured in milliseconds required by the TF to read the configuration, while everything in AM is hardcoded.
